all:
  hosts:
    vpn_node:
      ansible_connection: ssh
      ansible_host: 172.17.0.3
      ansible_user: root
      ansible_ssh_private_key_file: "./trusttunnel-key"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
